# Generated by Django 5.0.1 on 2024-01-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.test')),
            ],
        ),
    ]
