# Generated by Django 5.0.1 on 2024-02-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_test_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
