name: Publish docker image

on:
  push:
    branches: ['master']

jobs:
  build: 
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build
        run: docker-compose build
      
      - name: Run
        run: docker-compose run --rm app django-admin startproject core .

      - name: Up
        run: docker-compose up